server:
  port: 8787

spring:
  profiles:
    active: local

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:mysql://localhost:3366/sample?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always